name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ec2_host}}
          username: ${{ secrets.ec2_user }}
          key: ${{ secrets.ec2_key }}
          script: |
            cd ${{ secrets.app_path }}
            
            # Pull latest code
            git pull origin main
            
            # Backend deployment
            cd backend
            npm install
            pm2 restart backend || pm2 start app.js --name backend
            
            # Frontend deployment (React)
            cd ../frontend
            npm install
            npm run build
