name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY}}
          script: |
            cd ${{ secrets.APP_PATH }}
            
            # Pull latest code
            git pull origin main
            git pull --rebase origin main

            
            # Backend deployment
            cd ~/net/Backend
            npm install
            pm2 restart app.js || pm2 start app.js 
            
            # Frontend deployment (React)
            cd ~/net/Frontend/Frontend/
            npm install
            npm run build
